package com.example.subwaybooking.Activities;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.example.subwaybooking.DataModel.AllTrainModel;
import com.example.subwaybooking.DataModel.BookingDataModel;
import com.example.subwaybooking.R;
import com.example.subwaybooking.Util.Utils;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class BookTicket extends AppCompatActivity implements View.OnClickListener {

    AllTrainModel dataModel;
    TextView noOfSeats, price, departureCity, ArrivalCity, departureTime,
            arrivalTime, seatCount, bookBtn, priceTotal;
    ImageView addSeatBtn, removeSeatBtn, backBtn;
    int seatCounter = 0;
    int seatPrice = 0;
    int grandTotal = 0;
    DatabaseReference dbref;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_book_ticket);

        initView();
        setValues();
        setOnClick();
    }

    private void initView(){

        Bundle bundle = getIntent().getExtras();
        if (bundle != null){
            dataModel = (AllTrainModel) bundle.getSerializable("selectedData");
        }

        dbref = FirebaseDatabase.getInstance().getReference();

        backBtn = findViewById(R.id.backBtn);
        backBtn.setVisibility(View.VISIBLE);
        noOfSeats = findViewById(R.id.noOfSeats);
        price = findViewById(R.id.price);
        priceTotal = findViewById(R.id.priceTotal);
        departureCity = findViewById(R.id.departureCity);
        ArrivalCity = findViewById(R.id.ArrivalCity);
        departureTime = findViewById(R.id.departureTime);
        arrivalTime = findViewById(R.id.arrivalTime);
        seatCount = findViewById(R.id.seatCount);
        bookBtn = findViewById(R.id.bookBtn);
        addSeatBtn = findViewById(R.id.addSeatBtn);
        removeSeatBtn = findViewById(R.id.removeSeatBtn);

        seatPrice = Integer.parseInt(dataModel.getPrice());
    }

    private void setValues(){

        noOfSeats.setText(String.valueOf(dataModel.getNoOfSeats()));
        price.setText("Kr "+dataModel.getPrice());
        departureCity.setText(dataModel.getDepartureCity());
        ArrivalCity.setText(dataModel.getArrivalCity());
        departureTime.setText(dataModel.getDepartureTime());
        arrivalTime.setText(dataModel.getArrivalTime());
        seatCount.setText(String.valueOf(seatCounter));

    }

    private void setOnClick(){
        addSeatBtn.setOnClickListener(this);
        removeSeatBtn.setOnClickListener(this);
        bookBtn.setOnClickListener(this);
        backBtn.setOnClickListener(this);
    }

    private void bookTicketFunction(){

        String sCount = seatCount.getText().toString();

        if (sCount.equals("0")){
            seatCount.setError("please select number of seats");
            seatCount.requestFocus();
            return;
        }

        int seatCount = Integer.parseInt(sCount);

        final BookingDataModel model = new BookingDataModel();
        model.setId(dataModel.getId());
        model.setDepartureCity(dataModel.getDepartureCity());
        model.setArrivalCity(dataModel.getArrivalCity());
        model.setDepartureDate(dataModel.getDate());
        model.setDepartureTime(dataModel.getDepartureTime());
        model.setArrivalTime(dataModel.getArrivalTime());
        model.setNoOfSeats(seatCount);
        model.setBookingDate(Utils.getCurrentDate());
        model.setPrice(String.valueOf(grandTotal));

        final int newAvailableSeats = dataModel.getNoOfSeats() - seatCount;

        // sending request to firebase
        String requestId = dbref.push().getKey();
        model.setAutoGeneratedRequestID(requestId);
        dbref.child("MyBookings").child(requestId).setValue(model).addOnCompleteListener(new OnCompleteListener<Void>() {
            @Override
            public void onComplete(@NonNull Task<Void> task) {
                if (task.isSuccessful()){
                    Utils.showToast("Ticket Booked", true);

                    // setting new Available seats
                    dbref.child("routes").child(String.valueOf(dataModel.getId())).child("noOfSeats").setValue(newAvailableSeats);
                    finish();
                }
            }
        });




    }

    @Override
    public void onClick(View view) {
        switch (view.getId()){
            case R.id.addSeatBtn:
                if (seatCounter < 5) {
                    seatCounter++;
                    grandTotal = seatPrice * seatCounter;
                    seatCount.setText(String.valueOf(seatCounter));
                    priceTotal.setText("Kr "+grandTotal);
                }else {
                    Utils.showToast("book maximum 5 ticket at a time",false);
                }
                break;
            case R.id.removeSeatBtn:
                if (seatCounter > 0) {
                    seatCounter--;
                    grandTotal = seatPrice * seatCounter;
                    seatCount.setText(String.valueOf(seatCounter));
                    priceTotal.setText("Kr "+grandTotal);
                }else {
                    seatCount.setText("0");
                }
                break;
            case R.id.bookBtn:
                bookTicketFunction();
                break;

            case R.id.backBtn:
                onBackPressed();
                break;

        }
    }
}